import { chromium } from '@playwright/test'
const BASE = 'https://web-alpha-bay-87.vercel.app'
async function main() {
  const browser = await chromium.launch({ args: ['--no-sandbox', '--disable-dev-shm-usage'] })
  const page = await browser.newPage()
  await page.goto(`${BASE}/login`, { waitUntil: 'domcontentloaded' })
  await page.waitForTimeout(1200)
  const emailInput = page.locator('input[placeholder="you@school.edu"]')
  await emailInput.waitFor({ state: 'visible', timeout: 30_000 })
  await emailInput.fill('prod-final-1787626351@examforge-test.com')
  await page.fill('input[placeholder="Enter your password"]', 'SecurePass123!')
  await page.click('button[type="submit"]:has-text("Sign In")')
  await page.waitForURL((u) => !u.pathname.startsWith('/login'), { timeout: 60_000 })
  await page.waitForTimeout(4000)
  const navItem = page.locator('aside[aria-label="Main navigation"] nav a[href]').first()
  console.log('nav item count:', await navItem.count())
  await navItem.click({ button: 'right' })
  await page.waitForTimeout(800)
  const menuCount = await page.locator('[role="menu"]').count()
  const itemText = await page.locator('[role="menuitem"]').allTextContents()
  console.log('role=menu count:', menuCount, '| menu items:', itemText)
  await page.screenshot({ path: 'download/verification/omega-local/screenshots/omega4-context-menu.png' })
  await browser.close()
}
main().catch((e) => { console.error(e.message); process.exit(1) })
