const { chromium } = require('playwright')
;(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] })
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  await page.goto('http://localhost:3000/login', { waitUntil: 'domcontentloaded' })
  const emailInput = page.locator('input[placeholder="you@school.edu"]').first()
  await emailInput.waitFor({ state: 'visible', timeout: 30000 })
  await page.waitForTimeout(800)
  await emailInput.fill('prod-final-1787626351@examforge-test.com')
  await page.fill('input[placeholder="Enter your password"]', 'SecurePass123!')
  await page.click('button[type="submit"]:has-text("Sign In")')
  await page.waitForURL((url) => !url.pathname.startsWith('/login'), { timeout: 60000 })
  await page.waitForTimeout(2000)
  await page.goto('http://localhost:3000/exams/ba8630ba-37f6-427b-a929-3043d10ae5b2/take', { waitUntil: 'domcontentloaded' })
  await page.waitForTimeout(4000)
  const text = await page.evaluate(() => document.querySelector('main')?.innerText ?? 'NO MAIN')
  console.log('MAIN TEXT:', JSON.stringify(text))
  await page.screenshot({ path: 'download/verification/ux2/screenshots/debug-take-page.png' })
  await browser.close()
})()
