-- ═══════════════════════════════════════════════════════════════════════════
-- ExamForge AI Ω — Migration 004: Question ownership + AI-generation tracking
--
-- Problem: application code (dashboard-service, intelligent-insights,
-- question-bank-service, ai-teacher, billing-service, supabase/types.ts)
-- references questions.ai_generated and questions.created_by, but the
-- columns were never created. All such queries return 400.
--
-- Fix: add both columns with safe defaults + supporting indexes.
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. AI-generation flag (default false — existing rows are human-authored)
ALTER TABLE questions
  ADD COLUMN IF NOT EXISTS ai_generated boolean NOT NULL DEFAULT false;

-- 2. Authorship tracking (nullable — legacy rows have unknown authors)
ALTER TABLE questions
  ADD COLUMN IF NOT EXISTS created_by uuid
  REFERENCES auth.users(id) ON DELETE SET NULL;

-- 3. Indexes for the dashboard/query patterns
CREATE INDEX IF NOT EXISTS idx_questions_created_by ON questions(created_by);
CREATE INDEX IF NOT EXISTS idx_questions_ai_generated ON questions(ai_generated) WHERE ai_generated;

-- 4. Backfill: link existing questions to their exam's author where possible
UPDATE questions q
SET created_by = e.created_by
FROM exams e
WHERE q.exam_id = e.id
  AND q.created_by IS NULL
  AND e.created_by IS NOT NULL;

-- 5. RLS: questions row ownership follows the same policy model as exams
--    (existing policies already cover school-staff access; this adds
--     creator self-access for teachers)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'questions' AND policyname = 'Creators access own questions'
  ) THEN
    EXECUTE 'CREATE POLICY "Creators access own questions" ON questions
      FOR ALL TO authenticated
      USING (created_by = auth.uid())
      WITH CHECK (created_by = auth.uid())';
  END IF;
END $$;

COMMENT ON COLUMN questions.ai_generated IS 'true when the question was generated by an AI assistant (teacher-approved before publish)';
COMMENT ON COLUMN questions.created_by IS 'author user id — set automatically from exam author on backfill, explicit on direct creation';
